config/routes.rb
Redgrind::Application.routes.draw do
  resources :line_items

  resources :contacts
  resources :uploads
  
  get "work/index"
  get "services/index"
  get "about/index"

  
  match 'about'       => 'about#index'
  match 'work'        => 'work#index'
  match 'services'    => 'services#index'
  
  resources :screencasts
  
  devise_for :users
  

  root :to => "home#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability
 
  def initialize(user)
    user ||= User.new # guest user
 
    if user.role? :admin
      can :manage, :all
    elsif user.role? :author
      can :manage, Screencast
    else
      can :read, :all
    end
  end
end

app/models/authorship.rb
class Authorship < ActiveRecord::Base
  belongs_to :user
  belongs_to :screencast
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  
  def paypal_url(return_url)  
    values = {  
      :business => 'seller_1290899571_biz@gmail.com',  
      :cmd => '_cart',  
      :upload => 1,  
      :return => return_url,  
      :invoice => id  
    }  

    line_items.each_with_index do |item, index|  
      values.merge!({  
        "amount_#{index + 1}"      => item.unit_price,  
        "item_name_#{index + 1}"   => item.product.name,  
        "item_number_#{index + 1}" => item.product.identifier,  
        "quantity_#{index + 1}"    => item.quantity  
      })  
    end 
     
    "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.map { |k,v| "#{k}=#{v}"  }.join("&")  
  end
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :screencast_categories
  has_many :screencasts, :through => :screencast_categories
end

app/models/contact.rb
class Contact
  include Mongoid::Document
  field :name #:type => String (default)
  field :phone
  field :budget
  field :message
  field :email
  field :company
  field :deadline, :type => Date
  
  validates_presence_of :name, :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :screencast
  belongs_to :cart
end

app/models/movie_file.rb
class MovieFile < ActiveRecord::Base
  belongs_to :screencast
end

app/models/screencast.rb
class Screencast < ActiveRecord::Base
  has_many :screencast_categories
  has_many :categories, :through => :screencast_categories
  
  has_many :screencast_tags
  has_many :tags, :through => :screencast_tags
  
  has_many :authorships
  
  has_many :movie_files
  has_many :line_items
  
  accepts_nested_attributes_for :movie_files
  
  before_destroy :ensure_not_referenced_by_any_line_item
  
  def ensure_not_referenced_by_any_line_item
    if line_items.count.zero?
      return true
    else
      errors[:base] << "Line Items present"
      return false
    end
    
  end
  
end

app/models/screencast_category.rb
class ScreencastCategory < ActiveRecord::Base
  belongs_to :screencast
  belongs_to :category
end

app/models/screencast_tag.rb
class ScreencastTag < ActiveRecord::Base
  belongs_to :screencast
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :screencast_tags
  has_many :screencasts, :through => :screencast_tags
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  LOCAL_STORAGE_DIRECTORY = Rails.root.join('tmp') #'uploads'
  # #{RAILS_ROOT}/tmp/myfile_#{Process.pid}
  S3_ROOT_URL = 'http://s3.amazonaws.com/redgrind/screencasts/'

  after_save :upload_to_s3 #:create_job

  def self.store_locally(uploaded_data)
    file_path = LOCAL_STORAGE_DIRECTORY.join(uploaded_data.original_filename)
    File.open(file_path, 'wb+') { |file| file.write(uploaded_data.read) }
    
    file_path.to_s
  end

  def s3_key
    File.basename(local_path)
  end

  def upload_to_s3
    S3Upload.store(s3_key, open(local_path), :access => :public_read)
  end

  def s3_url
    S3_ROOT_URL + s3_key
  end

  def create_job
    Delayed::Job.enqueue S3UploadJob.new(id)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # accessible attributes for your model
  attr_accessible :email, :password, :password_confirmation #:remember_me
  
  scope :with_role, lambda { |role| {:conditions => "roles_mask & #{2**ROLES.index(role.to_s)} > 0 "}}
  
  ROLES = %w[admin author]
  
  def role_symbols
    roles.map(&:to_sym)
  end
  
  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.sum
  end
  
  def roles
    ROLES.reject { |r| ((roles_mask || 0) & 2**ROLES.index(r)).zero? }
  end
  
  def role?(role)
    roles.include? role.to_s
  end
  
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  
  layout 'application'
  
  def index
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.xml
  def index
    @contacts = Contact.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.xml
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.xml
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.xml
  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to(@contact, :notice => 'Contact was successfully created.') }
        format.xml  { render :xml => @contact, :status => :created, :location => @contact }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @contact.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.xml
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to(@contact, :notice => 'Contact was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @contact.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.xml
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to(contacts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/screencast_helper.rb
module ScreencastHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/work_helper.rb
module WorkHelper
end

app/views/contact/index.html.erb
<div class="secondary_page_bg">
	<div class="category_illustration">
    	<div class="punchline_contact">
        	<h2>Please contact us using the form below</h2>
            <p style="color:#CCC;">We answer every single message. We promise.</p>
        </div>
        
        <img class="phone" src="images/phone.png" width="216" height="159" alt="Contact" />
    </div>
<!-- .project -->
</div>
<!-- .LATEST_PROJECT -->

<div class="sec_menu">
	<div class="sec_menu_content">
    	<ul class="secondary_menu secondary_menu_contact">
        	<li><span>Our Address:</span> PO Box 13995 | Mill Creek, WA 98082-1995</li>
        	<li><span>Phone:</span> (425) 345-6764</li>
          <li><span>Email:</span> redgrind@gmail.com</li>
        </ul>
    </div>
    <!-- .sec_menu_content -->
</div>
<!-- .SEC_MENU -->

<div class="content">
	<div class="secondary_pages_content">
    	<h1>Have a project for us?</h1>
        <p class="subtitle">Get in touch and we'll send you a quote</p>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text. Ever since the 1500s, when an unknown printer took. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text. Ever since the 1500s, when an unknown printer took.</p>

	<div class="contact_box">
        	<div class="contact_box_top"></div>
            <div class="contact_box_middle">
            	<form action="" method="post" class="ajax_form" enctype="multipart/form-data">
                    <table class="contact_form" cellpadding="0" cellspacing="0">
                        <tr>
                            <td style="width:461px">
                            	<label for="name">Your name (required):</label>
                                <div class="form_input odd">
                                	<div class="input_left"></div>
                                    <input name="yourname" id="name" class="input_middle required" type="text" />
                                    <div class="input_right"></div>
                                </div>
                            </td>
                            
                            <td style="width:461px">
                            	<label for="email">Your email (required):</label>
                                <div class="form_input">
                                	<div class="input_left"></div>
                                    <input name="email" id="email" class="input_middle required" type="text" />
                                    <div class="input_right"></div>
                                </div>
                            </td>
                        </tr>
                        
                        <tr>
                            <td style="width:461px">
                            	<label for="phone">Your phone number:</label>
                                <div class="form_input odd">
                                	<div class="input_left"></div>
                                    <input name="phone" id="phone" class="input_middle" type="text" />
                                    <div class="input_right"></div>
                                </div>
                            </td>
                            
                            <td style="width:461px">
                            	<label for="company">Your company:</label>
                                <div class="form_input">
                                	<div class="input_left"></div>
                                    <input name="company" id="company" class="input_middle" type="text" />
                                    <div class="input_right"></div>
                                </div>
                            </td>
                        </tr>
                        
                        <tr>
                            <td style="width:461px">
                            	<label for="budget">Your budget:</label>
                                <div class="form_input odd">
                                	<div class="input_left"></div>
                                    <input name="Budget" id="budget" class="input_middle" type="text" />
                                    <div class="input_right"></div>
                                </div>
                            </td>
                            
                            <td style="width:461px">
                            	<label for="deadline">Deadline:</label>
                                <div class="form_input">
                                	<div class="input_left"></div>
                                    <input name="Deadline" id="deadline" class="input_middle" type="text" />
                                    <div class="input_right"></div>
                                </div>
                            </td>
                        </tr>
                        
                        <tr>
                        	<td style="width:922px" colspan="2">
                            	<label for="deadline">Your message:</label>
                            	<div class="form_textarea">
                                	<div class="textarea_left"></div>
                                    <textarea name="message" id="message" class="textarea_middle required" rows="5" cols="103"></textarea>
                                    <div class="textarea_right"></div>
                                </div>
                            </td>
                        </tr>
                        
                        <tr>
                        	<td style="width:922px" colspan="2">
                            	<input id="send" type="submit" class="submit" value="" />
                            </td>
                        </tr>
                    </table>
                </form>
            </div>
            <div class="contact_box_bottom"></div>
        </div>
        <!-- contact_box -->
</div>
    <!-- secondary_pages_content -->
    
    <div class="clear_container"></div>
    <br /><br />
    
</div>
<!-- .CONTENT -->

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul class="errors">
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table class="contact_form" cellpadding="0" cellspacing="0">
    <tr>
      <td style="width:461px">
      	<%= f.label :name, "Your name (required):" %>
        <div class="form_input odd">
          <div class="input_left"></div>
          <%= f.text_field :name, :class => "input_middle required" %>
          <div class="input_right"></div>
        </div>
      </td>      
      <td style="width:461px">
      	<%= f.label :email, "Your e-mail (required):" %>
        <div class="form_input">
        	<div class="input_left"></div>
          <%= f.text_field :email, :class => "input_middle required" %>
          <div class="input_right"></div>
        </div>
      </td>
    </tr>
    <tr>
      <td style="width:461px">
      	<%= f.label :phone, "Your phone number: " %>
        <div class="form_input odd">
        	<div class="input_left"></div>
          <%= f.text_field :phone, :class => "input_middle" %>
          <div class="input_right"></div>
        </div>
      </td>          
      <td style="width:461px">
        <%= f.label :company, "Company: " %>
        <div class="form_input">
        	<div class="input_left"></div>
          <%= f.text_field :company, :class=>"input_middle" %>
          <div class="input_right"></div>
        </div>
      </td>
    </tr>
    <tr>  
      <td style="width:461px">
      	<%= f.label :budget, "Budget: " %>
        <div class="form_input odd">
          <div class="input_left"></div>
          <%= f.text_field :budget, :class=> "input_middle" %>
          <div class="input_right"></div>
        </div>
      </td>          
      <td style="width:461px">
        <%= f.label :deadline, "Deadline: " %>
        <div class="form_input">
        	<%= f.date_select :deadline, :class => "input_middle" %>
        </div>
      </td>
    </tr>
    <tr>
    	<td style="width:922px" colspan="2">        
      	<%= f.label :message, "Your message (required): " %>
        <div class="form_textarea">
        	<div class="textarea_left"></div>
          <%= f.text_area :message, :id=>"message", :name=>"message", 
                          :class=>"textarea_middle required", :rows=>"5", :cols=>"103" %>
          <div class="textarea_right"></div>
        </div>    
      </td>
    </tr>
    <tr>
    	<td style="width:922px" colspan="2">
    	  <%= f.submit :id=>"send", :class=>"submit", :value=>"" %>
  	  </td>
    </tr>
  </table>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Phone</th>
    <th>Budget</th>
    <th>Message</th>
    <th>Email</th>
    <th>Company</th>
    <th>Deadline</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contacts.each do |contact| %>
  <tr>
    <td><%= contact.name %></td>
    <td><%= contact.phone %></td>
    <td><%= contact.budget %></td>
    <td><%= contact.message %></td>
    <td><%= contact.email %></td>
    <td><%= contact.company %></td>
    <td><%# contact.deadline %></td>
    <td><%= link_to 'Show', contact %></td>
    <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
    <td><%= link_to 'Destroy', contact, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<div class="secondary_page_bg">
  <div class="category_illustration">
  	<div class="punchline_contact">
      <h2>Contact us using the form below</h2>
      <p style="color:#CCC;">We answer every single message. That's a promise.</p>
    </div>
    <img class="phone" src="/images/phone.png" width="216" height="159" alt="Contact" />
  </div>
<!-- .project -->
</div>
<!-- .LATEST_PROJECT -->

<div class="sec_menu">
	<div class="sec_menu_content">
    	<ul class="secondary_menu secondary_menu_contact">
        	<li><span>Our Address:</span> PO Box 13995 | Mill Creek, WA 98082-1995</li>
        	<li><span>Ph:</span> 425.345.6764</li>
        	<li><span>Email:</span> redgrind@gmail.com</li>
        </ul>
    </div>
    <!-- .sec_menu_content -->
</div>
<!-- .SEC_MENU -->

<div class="content">
	<div class="secondary_pages_content">
    	<h1>Have a Screencast or Web Application project for us?</h1>
      <p class="subtitle">Request a quote below or let's just get in touch</p>

	<div class="contact_box">
        	<div class="contact_box_top"></div>
            <div class="contact_box_middle">
              <%= render 'form' %>
            </div>
            <div class="contact_box_bottom"></div>
        </div>
        <!-- contact_box -->
</div>
    <!-- secondary_pages_content -->
    
    <div class="clear_container"></div>
    <br /><br />
    
</div>
<!-- .CONTENT -->

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Name:</b>
  <%= @contact.name %>
</p>
<p>
  <b>Phone:</b>
  <%= @contact.phone %>
</p>
<p>
  <b>Budget:</b>
  <%= @contact.budget %>
</p>
<p>
  <b>Message:</b>
  <%= @contact.message %>
</p>
<p>
  <b>Email:</b>
  <%= @contact.email %>
</p>
<p>
  <b>Company:</b>
  <%= @contact.company %>
</p>
<p>
  <b>Deadline:</b>
  <%= @contact.deadline %>
</p>


<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>