config/routes.rb
Redgrind::Application.routes.draw do
  resources :line_items

  resources :contacts
  resources :uploads
  
  get "work/index"
  get "services/index"
  get "about/index"

  
  match 'about'       => 'about#index'
  match 'work'        => 'work#index'
  match 'services'    => 'services#index'
  
  resources :screencasts
  
  devise_for :users
  

  root :to => "home#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability
 
  def initialize(user)
    user ||= User.new # guest user
 
    if user.role? :admin
      can :manage, :all
    elsif user.role? :author
      can :manage, Screencast
    else
      can :read, :all
    end
  end
end

app/models/authorship.rb
class Authorship < ActiveRecord::Base
  belongs_to :user
  belongs_to :screencast
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  
  def paypal_url(return_url)  
    values = {  
      :business => 'seller_1290899571_biz@gmail.com',  
      :cmd => '_cart',  
      :upload => 1,  
      :return => return_url,  
      :invoice => id  
    }  

    line_items.each_with_index do |item, index|  
      values.merge!({  
        "amount_#{index + 1}"      => item.unit_price,  
        "item_name_#{index + 1}"   => item.product.name,  
        "item_number_#{index + 1}" => item.product.identifier,  
        "quantity_#{index + 1}"    => item.quantity  
      })  
    end 
     
    "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.map { |k,v| "#{k}=#{v}"  }.join("&")  
  end
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :screencast_categories
  has_many :screencasts, :through => :screencast_categories
end

app/models/contact.rb
class Contact
  include Mongoid::Document
  field :name #:type => String (default)
  field :phone
  field :budget
  field :message
  field :email
  field :company
  field :deadline, :type => Date
  
  validates_presence_of :name, :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :screencast
  belongs_to :cart
end

app/models/movie_file.rb
class MovieFile < ActiveRecord::Base
  belongs_to :screencast
end

app/models/screencast.rb
class Screencast < ActiveRecord::Base
  has_many :screencast_categories
  has_many :categories, :through => :screencast_categories
  
  has_many :screencast_tags
  has_many :tags, :through => :screencast_tags
  
  has_many :authorships
  
  has_many :movie_files
  has_many :line_items
  
  accepts_nested_attributes_for :movie_files
  
  before_destroy :ensure_not_referenced_by_any_line_item
  
  def ensure_not_referenced_by_any_line_item
    if line_items.count.zero?
      return true
    else
      errors[:base] << "Line Items present"
      return false
    end
    
  end
  
end

app/models/screencast_tag.rb
class ScreencastTag < ActiveRecord::Base
  belongs_to :screencast
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :screencast_tags
  has_many :screencasts, :through => :screencast_tags
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  LOCAL_STORAGE_DIRECTORY = Rails.root.join('tmp') #'uploads'
  # #{RAILS_ROOT}/tmp/myfile_#{Process.pid}
  S3_ROOT_URL = 'http://s3.amazonaws.com/redgrind/screencasts/'

  after_save :upload_to_s3 #:create_job

  def self.store_locally(uploaded_data)
    file_path = LOCAL_STORAGE_DIRECTORY.join(uploaded_data.original_filename)
    File.open(file_path, 'wb+') { |file| file.write(uploaded_data.read) }
    
    file_path.to_s
  end

  def s3_key
    File.basename(local_path)
  end

  def upload_to_s3
    S3Upload.store(s3_key, open(local_path), :access => :public_read)
  end

  def s3_url
    S3_ROOT_URL + s3_key
  end

  def create_job
    Delayed::Job.enqueue S3UploadJob.new(id)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # accessible attributes for your model
  attr_accessible :email, :password, :password_confirmation #:remember_me
  
  scope :with_role, lambda { |role| {:conditions => "roles_mask & #{2**ROLES.index(role.to_s)} > 0 "}}
  
  ROLES = %w[admin author]
  
  def role_symbols
    roles.map(&:to_sym)
  end
  
  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.sum
  end
  
  def roles
    ROLES.reject { |r| ((roles_mask || 0) & 2**ROLES.index(r)).zero? }
  end
  
  def role?(role)
    roles.include? role.to_s
  end
  
end

app/controllers/screencasts_controller.rb
class ScreencastsController < ApplicationController
  
  layout 'application'
  
  def index
    @screencasts = Screencast.all
    @s3base = "http://s3.amazonaws.com/redgrind/screencasts/images"
  end
  
  def new
    @screencast = Screencast.new
    @screencast.movie_files.build
  end
  
  def edit
    @screencast = Screencast.find(params[:id])
  end
  
  def create
    #raise params[:screencast][:movie_files_attributes]["0"][:path].to_s
    mov_file = params[:screencast][:movie_files_attributes]["0"][:path]
    @screencast = Screencast.new(params[:screencast])
    
    if @screencast.save
      flash[:notice] = "Successfully saved screencast"
      #m4v_file = params[:upload][:m4vfile]
      @upload = Upload.new(:local_path => Upload.store_locally(mov_file))
      @upload.save!
      redirect_to @screencast
    else
      render :action => 'new'
    end
  end
  
  def update
    #rails params.to_yaml
    @screencast = Screencast.find(params[:id])
    if @screencast.update_attributes(params[:screencast])
      flash[:notice] = "Successfully updated screencast"
      redirect_to @screencast
    else
      render :action => 'edit'
    end
  end
  
  def show
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/screencast_helper.rb
module ScreencastHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/work_helper.rb
module WorkHelper
end

app/views/screencasts/_form.html.erb
<%= form_for @screencast, :html => { :multipart => true } do |f| %>  
  <% if @screencast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@screencast.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul class="errors">
      <% @screencast.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <table class="contact_form" cellpadding="0" cellspacing="0">
    <tr>
      <td style="width:461px">
      	<%= f.label :name, "Screencast name (required):" %>
        <div class="form_input odd">
          <div class="input_left"></div>
          <%= f.text_field :name, :class => "input_middle required" %>
          <div class="input_right"></div>
        </div>
      </td>      
      <td style="width:461px">
      	<%= f.label :small_screenshot, "Small screenshot:" %>
        <div class="form_input">
        	<div class="input_left"></div>
          <%= f.text_field :small_screenshot, :class => "input_middle required" %>
          <div class="input_right"></div>
        </div>
      </td>
    </tr>
    <tr>
      <td style="width:461px">
      	<%= f.label :large_screenshot, "Large screenshot: " %>
        <div class="form_input odd">
        	<div class="input_left"></div>
          <%= f.text_field :large_screenshot, :class => "input_middle" %>
          <div class="input_right"></div>
          <div><%# f.file_field :mov %></div>
        </div>
      </td>
      
      
      <%#
      t.integer  "screencast_id"
      t.string   "name"
      t.string   "path"
      t.string   "extension"
      t.datetime "created_at"
      t.datetime "updated_at"
      %>
      
      <td style="width:461px">
      	<%= f.label :movie_files, "Movies:" %>
        <div>
          <!-- file_field_tag 'user_pic', :accept => 'image/png,image/gif,image/jpeg' -->
          <%# file_field_tag 'screencast[file]' %> 
          <% f.fields_for :movie_files do |movie_form| %>
            <%= movie_form.file_field :path %>
            <%= movie_form.hidden_field :extension, :value => ".mov" %>
          <% end %>
        </div>
        <div>
          .m4v: <%# file_field_tag, 'screencast[movie_file_ids][]', 'm4v' %>
        </div>   
      </td>  
      
       
    </tr>
    <tr>  
      <td style="width:461px">
      	<%= f.label :cost_in_pennies, "Cost (pennies): " %>
        <div class="form_input odd">
          <div class="input_left"></div>
          <%= f.text_field :cost_in_pennies, :class=> "input_middle" %>
          <div class="input_right"></div>
        </div>
      </td>          
      <td style="width:461px">
        <%= f.label :published_on, "Published Date: " %>
        <div class="form_input">
        	<%= f.date_select :published_on, :class => "input_middle" %>
        </div>
      </td>
    </tr>
    <tr>
    	<td style="width:922px" colspan="2">        
      	<%= f.label :description, "Description (required): " %>
        <div class="form_textarea">
        	<div class="textarea_left"></div>
          <%= f.text_area :description, :id=>"description", :name=>"description", 
                          :class=>"textarea_middle required", :rows=>"5", :cols=>"103" %>
          <div class="textarea_right"></div>
        </div>    
      </td>
    </tr>
    <tr>
      <td style="width:922px;" colspan="2">
        <h2>Categories</h2>
        <% for category in Category.all %>
          <span>
            <%= check_box_tag 'screencast[category_ids][]', category.id, 
                  @screencast.categories.include?(category) %> <%= category.name %> 
          </span> &nbsp;&nbsp;
        <% end %>
      </td>
    </tr>
    <tr>
      <td style="width:922px;" colspan="2">
        <h2>Tags</h2>
        <% for tag in Tag.all %>
          <span>
            <%= check_box_tag 'screencast[tag_ids][]', tag.id, 
                  @screencast.tags.include?(tag) %> <%= tag.name %> 
          </span> &nbsp;&nbsp;
        <% end %>
      </td>
    </tr>
    <tr>
    	<td style="width:922px" colspan="2">
    	  <%= f.submit :id=>"send", :value=>"Upload Screencast" %>
  	  </td>
    </tr>
  </table>
<% end %>

app/views/screencasts/edit.html.erb
<div class="sec_menu">
	<div class="sec_menu_content">
    <ul class="secondary_menu secondary_menu_contact">
      <li>edit a new screencast</li>
    </ul>
  </div>
</div>

<div class="content">
  <div class="secondary_pages_content">
    <h1>One step closer to earning some dough</h1>
    
    <div class="contact_box">
      <div class="contact_box_top"></div>
      <div class="contact_box_middle">
        <%= render 'form' %>
      </div>
      <div class="contact_box_bottom"></div>
    </div> <!-- /contact_box -->
  </div> <!-- /secondary_pages_content -->
  <div class="clear_container"></div>
</div><!-- .CONTENT -->

app/views/screencasts/index.html.erb
<div class="secondary_page_bg">
	<div class="category_illustration">
    <img class="laptop png" src="/images/laptop.png" width="379" height="113" alt="About us" />
  	<div class="punchline_work">
      <h2>RedGrind Screencasts</h2>
      <p style="color:#BBB;">Producing approximately 1 <strong>screencast</strong> per month</p>
    </div>
  </div> <!-- .project -->
</div> <!-- .LATEST_PROJECT -->

<div class="sec_menu">
	<div class="sec_menu_content">
  	<ul class="secondary_menu">
    	<li><span>Screencasts:</span></li>
      <li class="sec_menu_selected">
        <div class="sec_menu_selected_left"></div>
        <div class="sec_menu_selected_middle">All</div>
        <div class="sec_menu_selected_right"></div>
      </li>
      <!--
      <li class="sec_menu_selected">
        <div class="sec_menu_selected_left"></div>
        <div class="sec_menu_selected_middle">Web</div>
        <div class="sec_menu_selected_right"></div>
      </li>
      <li><a href="#">Productivity</a></li>
      <li><a href="#">Rails</a></li>
      -->
    </ul>
  </div> <!-- .sec_menu_content -->
</div> <!-- .SEC_MENU -->

<div class="content">
  <div class="secondary_pages_content">
	  <% num = 0 %>
	  <% for screencast in @screencasts %>
	    <% num += 1 %>
	    <div class="work_project <% if num%3 == 0 %>last_project<% end %>"> 
	      <!--
      	<a class="project_hover" href="images/projects/project1_lightbox.jpg" rel="lightbox[roadtrip1]" title="Online electronics shop">&nbsp;</a>
      	<%# link_to ""%>
      	-->
      	<!--
      	<a href="images/projects/project2_lightbox.jpg" rel="lightbox[roadtrip1]" title="Online electronics shop"></a>
      	-->
      	<%# link_to "", "#{@s3base}/#{screencast.small_screenshot}", :class => "project_title" %>
      	<%= image_tag "#{@s3base}/#{screencast.small_screenshot}", :alt => screencast.name %>
      	<%= link_to "#{screencast.name}", screencast, :class => "project_title" %>
      	<span class="cost">
      	  <%=h number_to_currency screencast.cost_in_pennies/100, :unit => '$', :separator => ".", :delimiter => "," %>
      	  | <%= link_to "preview #{screencast.name}"%>
      	</span>
      	<div align="right">
      	  <form action="https://www.paypal.com/cgi-bin/webscr" method="post">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="4N58XVW7TQKWU">
            <input type="image" src="https://www.paypal.com/en_US/i/btn/btn_buynow_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
            <img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1">
          </form>
          
          
      	</div>
        <p><%= screencast.description %></p>
      </div> <!-- .work_project -->
      
      <% if num%3 == 0 %>
        <div class="clear_container"></div><br /><br />
      <% end %>
      
	  <% end %>
	  
    <div class="clear_container"></div>
    </div>
</div>
<!-- .CONTENT -->

app/views/screencasts/new.html.erb
<% if can? :update, @screencast %>

  <div class="sec_menu">
  	<div class="sec_menu_content">
      <ul class="secondary_menu secondary_menu_contact">
        <li>upload a new screencast</li>
      </ul>
    </div>
  </div>

  <div class="content">
    <div class="secondary_pages_content">
      <h1>One step closer to earning some dough</h1>
    
      <div class="contact_box">
        <div class="contact_box_top"></div>
        <div class="contact_box_middle">
          <%= render 'form' %>
        </div>
        <div class="contact_box_bottom"></div>
      </div> <!-- /contact_box -->
    </div> <!-- /secondary_pages_content -->
    <div class="clear_container"></div>
  </div><!-- .CONTENT -->

<% else %>
  <div class="content"><%= render "shared/unauthorized" %></div>
<% end %>

app/views/screencasts/show.html.erb
Show