config/routes.rb
Redgrind::Application.routes.draw do
  resources :line_items

  resources :contacts
  resources :uploads
  
  get "work/index"
  get "services/index"
  get "about/index"

  
  match 'about'       => 'about#index'
  match 'work'        => 'work#index'
  match 'services'    => 'services#index'
  
  resources :screencasts
  
  devise_for :users
  

  root :to => "home#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability
 
  def initialize(user)
    user ||= User.new # guest user
 
    if user.role? :admin
      can :manage, :all
    elsif user.role? :author
      can :manage, Screencast
    else
      can :read, :all
    end
  end
end

app/models/authorship.rb
class Authorship < ActiveRecord::Base
  belongs_to :user
  belongs_to :screencast
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  
  def paypal_url(return_url)  
    values = {  
      :business => 'seller_1290899571_biz@gmail.com',  
      :cmd => '_cart',  
      :upload => 1,  
      :return => return_url,  
      :invoice => id  
    }  

    line_items.each_with_index do |item, index|  
      values.merge!({  
        "amount_#{index + 1}"      => item.unit_price,  
        "item_name_#{index + 1}"   => item.product.name,  
        "item_number_#{index + 1}" => item.product.identifier,  
        "quantity_#{index + 1}"    => item.quantity  
      })  
    end 
     
    "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.map { |k,v| "#{k}=#{v}"  }.join("&")  
  end
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :screencast_categories
  has_many :screencasts, :through => :screencast_categories
end

app/models/contact.rb
class Contact
  include Mongoid::Document
  field :name #:type => String (default)
  field :phone
  field :budget
  field :message
  field :email
  field :company
  field :deadline, :type => Date
  
  validates_presence_of :name, :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :screencast
  belongs_to :cart
end

app/models/movie_file.rb
class MovieFile < ActiveRecord::Base
  belongs_to :screencast
end

app/models/screencast.rb
class Screencast < ActiveRecord::Base
  has_many :screencast_categories
  has_many :categories, :through => :screencast_categories
  
  has_many :screencast_tags
  has_many :tags, :through => :screencast_tags
  
  has_many :authorships
  
  has_many :movie_files
  has_many :line_items
  
  accepts_nested_attributes_for :movie_files
  
  before_destroy :ensure_not_referenced_by_any_line_item
  
  def ensure_not_referenced_by_any_line_item
    if line_items.count.zero?
      return true
    else
      errors[:base] << "Line Items present"
      return false
    end
    
  end
  
end

app/models/screencast_tag.rb
class ScreencastTag < ActiveRecord::Base
  belongs_to :screencast
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :screencast_tags
  has_many :screencasts, :through => :screencast_tags
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  LOCAL_STORAGE_DIRECTORY = Rails.root.join('tmp') #'uploads'
  # #{RAILS_ROOT}/tmp/myfile_#{Process.pid}
  S3_ROOT_URL = 'http://s3.amazonaws.com/redgrind/screencasts/'

  after_save :upload_to_s3 #:create_job

  def self.store_locally(uploaded_data)
    file_path = LOCAL_STORAGE_DIRECTORY.join(uploaded_data.original_filename)
    File.open(file_path, 'wb+') { |file| file.write(uploaded_data.read) }
    
    file_path.to_s
  end

  def s3_key
    File.basename(local_path)
  end

  def upload_to_s3
    S3Upload.store(s3_key, open(local_path), :access => :public_read)
  end

  def s3_url
    S3_ROOT_URL + s3_key
  end

  def create_job
    Delayed::Job.enqueue S3UploadJob.new(id)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # accessible attributes for your model
  attr_accessible :email, :password, :password_confirmation #:remember_me
  
  scope :with_role, lambda { |role| {:conditions => "roles_mask & #{2**ROLES.index(role.to_s)} > 0 "}}
  
  ROLES = %w[admin author]
  
  def role_symbols
    roles.map(&:to_sym)
  end
  
  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.sum
  end
  
  def roles
    ROLES.reject { |r| ((roles_mask || 0) & 2**ROLES.index(r)).zero? }
  end
  
  def role?(role)
    roles.include? role.to_s
  end
  
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  
  layout 'application'
  
  def index
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/screencast_helper.rb
module ScreencastHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/work_helper.rb
module WorkHelper
end

app/views/about/_our_process.html.erb
<h1>Here's our Process</h1>
<p class="subtitle"></p>
<img class="the_process" src="images/the_process.jpg" alt="The process we follow" title="The process" />

app/views/about/_ruby_on_rails.html.erb
<img class="newspaper_icon png" src="images/rails.png" alt="Rails" />
<h1>Ruby on Rails</h1>
<p class="subtitle">We are a Ruby on Rails Web Application Development shop</p>
<div class="clear_container"></div>

<div class="two_columns">
	<div class="text">
	  <h6>Why Ruby on Rails?</h6>
    <p>
      Ruby on Rails allows us to develop, test, and deploy web applications the right way and do so
      efficiently. Updates and revisions can be made
      nearly instantaneously, tailoring the application to the clients’ needs. Our partners and clients
      appreciate seeing working prototypes after just a few days into the project. Ruby Rails espouses 
      pragmatism throughout the framework resulting in more enjoyable programming, which makes us eager
      to grow your project and take on the next project.  When practiced properly Rails results in 
      quality, scalable web applications.
    </p>
    <p>
      Start your business and web application on the right track -- 
      <%= link_to "contact RedGrind", new_contact_path %> to get started!
    </p>
  </div>
  
  <%= render 'about/testimonials'%>
</div> <!-- /two_columns -->
<div class="clear_container"></div>

app/views/about/_services.html.erb
<div class="services_we_offer">
  <h5>The services we offer</h5>
  <p>We can help you in the following domains:</p> 
  <div class="box">
    <div class="box_top"></div>
    <div class="box_middle">
      <ul class="third_menu">
        <li><a href="services">Web Application Development</a></li>
        <li class="first"><a href="services">Screencast Production</a></li>
      </ul>
    </div>
    <div class="box_bottom"></div>
  </div> <!-- /box -->
</div>

app/views/about/_social.html.erb
<div class="social_header_links">
	<div class="follow_us">Get to know us better:</div>
  <ul class="about_social_network">
    <li><a class="twitter_header" target="_blank" href="http://twitter.com/markholton"></a></li>
  	<li><a class="flickr_header" target="_blank" href="http://www.flickr.com/photos/53234803@N05/"></a></li>
  	<li><a class="linkedin_header" target="_blank" href="http://www.linkedin.com/profile/view?id=32021710"></a></li>
  	<li><a class="facebook_header" target="_blank" href="http://www.facebook.com/pages/EyeOnMajorscom/104616299076"></a></li>
  </ul>
</div>

app/views/about/_testimonials.html.erb
<div class="services_we_offer">
	<h5>RedGrind Mission</h5>
    <div class="box">
    	<div class="box_top"></div>
      <div class="box_middle">
        <div class="testimonials">
          <img class="cite_icon png" src="images/cite_icon.png" width="21" 
               height="19" alt="Citation" />
          <cite>
            You want to work with a partner who understands your small business needs.  We get to know what your
            goals are, and work to understand how a web application fits into your broader goal.  
            RedGrind only accept a limited number of projects where we feel confident we can help make you a success.  
          </cite>
          <h6 class="testimonial_name">Mark Holton, RedGrind</h6>
          <div class="clear_container"></div>
        </div>
      </div>
      <div class="box_bottom"></div>
    </div><!-- /box --> 
</div>

app/views/about/index.html.erb
<div class="secondary_page_bg">
	<div class="category_illustration">
    <div class="punchline_about">
      <h2>Need a web application or screencast?</h2>
      <p>We kill it, so you can eat</p>
    </div>        
    <img class="drawing_tablet" src="images/drawing_tablet.png" width="317" height="159" alt="About us" />
  </div>
</div>
<%# render 'about/'%>

<%= render 'layouts/sub_menu' %>

<div class="content">
	<div class="secondary_pages_content">
	  <h1>Who is RedGrind</h1>
    <p class="subtitle">A Web Application and Screencasting Development boutique</p>
    <div class="clear_container"></div>
    
    <div class="two_columns">
      <div class="text">
        <h5>About RedGrind</h5>
        <p>
          RedGrind was formed from a lifelong passion for entrepreneurial web application development.
          Initially, Mark Holton works on the majority of the work on RedGrind projects, 
          as the founding partner of RedGrind, LLC.  Mark has been building N-tier web applications 
          since 2001 in various technologies for companies such as Boeing, Qwest, and AT&T.  
          RedGrind started as an outlet in post-day-job-work-hours at night and the weekend towards a true 
          passion for creating great web applications.
          In 2006, after encountering Ruby on Rails, quickly became serious about writing Rails
          applications and searched for as much experience and learning as he could outside of work hours.
          This included completing a 9 month, three course University of Washington Certificate
          program in Ruby development, and attending two RailsConf's in Portland and Baltimore.  
          While practicing and progressing in Rails development, 
          followed up with a repeat effort in Rails and Test Driven Rails Development at UW taught 
          by Rails core contributors.  
          Throughout that time writing Rails code nearly every night and deploying 
          to the cloud every week. 
        </p>
        <p>
          Throughout all this time in web development, we have picked up knowledge that we choose
          to share.  This is where our passion for <%= link_to "screencasting", screencasts_path %> 
          comes in, the best medium for 
          communicating and sharing software ideas!  
        </p>
        
      </div>
      
      <%= render 'about/services' %>
    </div> <!-- /two_columns -->
    
    <div class="clear_container"></div><br /><br />
    
    <%= render 'about/ruby_on_rails'%>
    <div class="clear_container"></div><br /><br />
    
    <div class="one_column">
      <%= render 'about/our_process' %>
    </div>
    
    
  </div><!-- /secondary_pages_content -->
    
  <div class="clear_container"></div>
    
</div>
<!-- .CONTENT -->